### ISSUE TITLE
Add a 'create branch' task

### ISSUE THREAD

**Issue by sgillespie** [nebula-plugins/gradle-stash-plugin#5]
I currently use gradle to automate the creation of branches, but at the moment I use jgit to clone locally.  On very large repositories this takes a very long time.  If possible (and if it makes sense), I'd like to use this plugin for that purpose.

To me, it makes sense to include a 'create branch' task in this project.  Otherwise, I can just create a plugin that extends this one.

**Comment by jmcgarr** [comment]
Closing.
